version: "3.8"
services:

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - c:/data/db:/data/db
      - c:/data/configdb:/data/configdb
    ports:
      - 27017:27017
    restart: unless-stopped

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  backendapplication:
    image: backendapplication
    container_name: backendapplication
    depends_on:
      - mongo
    ports:
      - 8080:8080